#!/usr/bin/env python3
"""Compose LEDGER.md — the both-axes versioning ledger. DOCUMENTS ONLY.

Two inputs, one output:
  LEDGER_DATA.json     curated both-axes facts (architecture entries + instance
                       entries: world hash, LAMBDA, gates, renders)
  VERSION_LEDGER.jsonl the append-only per-edit trail (written by the every-edit
                       PostToolUse hook, scripts/ledger_hook.py)
  -> LEDGER.md         human-readable ledger: architecture table, instances per
                       architecture, and the per-edit trail.

This never builds or audits and never edits code — it only renders a document.
The hook calls it after each edit so LEDGER.md tracks BOTH axes at every edit.
"""
from __future__ import annotations
import json
import os
from collections import defaultdict

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(REPO, "LEDGER_DATA.json")
TRAIL = os.path.join(REPO, "VERSION_LEDGER.jsonl")
OUT = os.path.join(REPO, "LEDGER.md")


def _lam(d: dict) -> str:
    return ", ".join(f"{k}={v}" for k, v in d.items())


def build() -> str:
    data = json.load(open(DATA, encoding="utf-8"))
    lines = []
    lines.append("# LEDGER — both-axes versioning record")
    lines.append("")
    lines.append("Auto-generated by `scripts/build_ledger.py` (documents only; never "
                 "builds or audits). Curated facts live in `LEDGER_DATA.json`; the "
                 "per-edit trail is appended by the every-edit hook "
                 "(`scripts/ledger_hook.py` → `VERSION_LEDGER.jsonl`). Two axes: "
                 "**architecture/implementation versions** and the **instances** "
                 "(corpus/genre trained models) under each.")
    lines.append("")

    # --- Incidents (fabrication-class remediations, on the record) ---
    incidents = data.get("incidents", [])
    if incidents:
        lines.append("## Incidents (fabrication-class, on the record)")
        lines.append("")
        for inc in incidents:
            lines.append(f"- **{inc.get('date','')} — {inc.get('id','')}**: "
                         f"{inc.get('note','')}")
        lines.append("")

    # --- Axis 1: architecture versions ---
    lines.append("## Axis 1 — architecture / implementation versions")
    lines.append("")
    lines.append("| Version | Location | Marker | Driving directive | Audit |")
    lines.append("|---|---|---|---|---|")
    for a in data.get("architectures", []):
        lines.append(f"| **{a['version']}** | {a['location']} | {a['marker']} | "
                     f"{a['driving_directive']} | {a['audit']} |")
    lines.append("")

    # --- Axis 2: instances, grouped under their architecture ---
    lines.append("## Axis 2 — instances (corpus → trained model), per architecture")
    lines.append("")
    by_arch = defaultdict(list)
    for i in data.get("instances", []):
        by_arch[i["architecture"]].append(i)
    for arch in by_arch:
        lines.append(f"### under {arch}")
        lines.append("")
        for i in by_arch[arch]:
            lines.append(f"- **{i['name']}** — corpus: {i['corpus']}")
            if i.get("role"):
                lines.append(f"  - role: {i['role']}")
            lines.append(f"  - location: {i['location']}")
            lines.append(f"  - world: content-hash `{i['world_content_hash']}`, "
                         f"M={i['world_M']} anchors")
            lines.append(f"  - LAMBDA: {_lam(i['lambda'])}")
            lines.append(f"  - gates: {i['gates']}")
            lines.append(f"  - renders: {i['renders']}")
        lines.append("")

    # --- per-edit trail (auto) ---
    lines.append("## Per-edit trail (auto, append-only)")
    lines.append("")
    lines.append("Every tracked-file edit, newest last, grouped by the git HEAD it "
                 "was made against. Notes (pivots, renames) are interleaved.")
    lines.append("")
    entries = []
    if os.path.exists(TRAIL):
        for ln in open(TRAIL, encoding="utf-8"):
            ln = ln.strip()
            if not ln:
                continue
            try:
                entries.append(json.loads(ln))
            except Exception:
                continue
    by_head = defaultdict(list)
    order = []
    for e in entries:
        h = e.get("head", "?")
        if h not in by_head:
            order.append(h)
        by_head[h].append(e)
    for h in order:
        lines.append(f"### at `{h}`")
        for e in by_head[h]:
            ts = e.get("ts", "")
            if e.get("tool") in ("note", "genesis"):
                lines.append(f"- _{e.get('tool')}_ ({ts}): {e.get('note', '')}")
            else:
                lines.append(f"- `{e.get('tool')}` {e.get('path','')} ({ts})")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    try:
        md = build()
    except Exception as exc:            # never break a caller (e.g. the hook)
        import sys
        print(f"build_ledger: {exc}", file=sys.stderr)
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(md)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
